### ISSUE TITLE
module 'discord.ext.commands' has no attribute 'hybrid_group'

### ISSUE THREAD

**Issue by flamingowrangler2869** [aleeeuwu/AleBot#10]
```
C:\msys64\home\MERSENNE_\AleBot>py main.py
Traceback (most recent call last):
  File "C:\msys64\home\MERSENNE_\AleBot\main.py", line 5, in <module>
    from botcmds.privilege import admin_check
  File "C:\msys64\home\MERSENNE_\AleBot\botcmds\privilege.py", line 13, in <module>
    @commands.hybrid_group(description='Checks to see if you are a privileged user')
     ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'discord.ext.commands' has no attribute 'hybrid_group'
```

**Comment by TCAtrevor** [comment]
Do you have the latest discord.py?
